server {
    listen 80;
    server_name _;

    location = / {
        return 301 https://kubamichalowski.pl;
    }

    location = /status {
        return 200 "ok";
    }

    location / {
        root /data;
        try_files $uri =404;
        add_header X-Robots-Tag "noindex, nofollow, noarchive";
    }
}